matrix:
  include:
    - language: java
      arch:
        - amd64
        - ppc64le
        
      # jdk:
      #  - oraclejdk8
      sudo: false
      dist: trusty
      script: mvn -f java/pom.xml verify
      cache:
        directories:
          - '$HOME/.m2/repository'

    - language: csharp
      mono: none
      dist: xenial
      dotnet: 2.2
      script: dotnet test dotnet/Razorvine.Pyrolite/Tests
